### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by epintos** [whitesmith/rubycritic#103]
Hi,

I would like to contribute with some features but it will be nice to see a Roadmap of the new features that you have in mind. Do you have anything similar?

Best

**Comment by troessner** [comment]
There is no real roadmap at the moment, at least not one that the current maintainers have discussed and agreed on.
There is the old one from the initial author @guilhermesimoes that you can find [here](https://github.com/whitesmith/rubycritic/wiki/Roadmap) and just by skimming it I'm sure that we want 95% of that one as well ;)

To come back to your wish to contribute: Our [issues](https://github.com/whitesmith/rubycritic/issues) are up to date and well-groomed, why not just pick one? You could start with #97 and #77 to get a feeling for RubyCritic and then advance from there.

**Comment by troessner** [comment]
@epintos I labeled all issues in question with "documentation", would be great if you could pick some up!
That way you'd also **really** get to know RubyCritic ;)

**Comment by epintos** [comment]
@troessner Thanks for the response! As soon as I have some free time I will start looking at those issues.

**Comment by Onumis** [comment]
We now maintain the roadmap in the repo: https://github.com/whitesmith/rubycritic/blob/master/ROADMAP.md
