### ISSUE TITLE
Explain GPA / score

### ISSUE THREAD

**Issue by troessner** [whitesmith/rubycritic#104]
We did merge #35 but funny guys that we are we nowhere explain to the user what the hell a "score" means for us.
Let's fix this ;)

**Comment by Onumis** [comment]
This is very closely related to #63, we can probably just close this...

**Comment by Onumis** [comment]
Added a wiki page with the proposed docs.
(https://github.com/whitesmith/rubycritic/wiki/Rating-and-Score)
