### ISSUE TITLE
"Open with browser" problem in our local development environment

### ISSUE THREAD

**Issue by troessner** [whitesmith/rubycritic#110]
Unfortunately it seems like our recent [open html with browser](https://github.com/whitesmith/rubycritic/pull/100) pull request introduced a problem in our development environment:

On running 

>> bundle exec rake 

locally on my machine Safari opens with the error that you can see attached in the screenshot.

<img width="712" alt="screen shot 2016-01-23 at 17 56 28" src="https://cloud.githubusercontent.com/assets/271109/12531452/4ba9519c-c1fb-11e5-94ca-59a22d40fb46.png">

Something like

>> bin/rubycritic lib/

works fine though

@superiorlu do you have time to look into this?

**Comment by superiorlu** [comment]
hi, @troessner my safari not have this problem. my mac osx 10.10.5 and safari 8.0.8 
i find this [http://comphelp.org/wiki/wiki.php?kw=Safari%20Kcferrordomaincfnetwork%20Error%201#2](http://comphelp.org/wiki/wiki.php?kw=Safari%20Kcferrordomaincfnetwork%20Error%201#2) may be helpful for you.

**Comment by troessner** [comment]
Sorry, I phrased this poorly. What I was hinting at was that when running our tests **no** browser should open at all. Instead, this functionality should be stubbed out as usual with "kind of" external dependencies.

Actually I'm the one to blame here since I missed this in my review big time ;)

Do you have time to look into this?

**Comment by Onumis** [comment]
Yeah I also should have payed more attention to this one.
Here's a few other things that bug me:

- the command does not terminate until the browser is closed
- using the flag `--mode-ci` still opens on the browser - this is bad because it may cause problems with users that integrated RubyCritic as part of their CI
- maybe we should have the options to do `--open none` or `--open false` to skip the opening on a browser

I'm holding on #108 for now because I feel this change will make some users angry that already integrated RubyCritic into their tools, like @RobertoSchneiders for example (https://github.com/whitesmith/rubycritic/issues/98#issue-126243425)

**Comment by RobertoSchneiders** [comment]
Yeah, open the browser on `--mode-ci` will probably break or hang the build.

**Comment by superiorlu** [comment]
@troessner  okay i take it.
@Onumis  if default run ```rubyciritc```  not open browser, only people run ```rubycritic -O safari``` ，can open report file in browser.  this is meet the requirements?

**Comment by troessner** [comment]
>> I'm holding on #108 for now because I feel this change will make some users angry - those that already integrated RubyCritic into their tools, like @RobertoSchneiders for example (#98 (comment))

Good call!

>>  if default run rubyciritc not open browser, only people run rubycritic -O safari ，can open report file in browser. this is meet the requirements?

:+1: 

We can also leave out the argument to "-O" which then would open up the default browser.

**Comment by superiorlu** [comment]
@troessner  your mean is: run ```rubycritic -O ``` will open up default browser？

**Comment by Onumis** [comment]
The thing is, I actually like that it opens the browser automatically on "standalone" (I lack a proper term for this) runs. 

What I mean is that, casual users do not want to specify that flag.
Power-users are the ones that should have to deal with the options, and currently, they cannot switch off this feature.

**Comment by troessner** [comment]
>> What I mean is that, casual users do not want to specify that flag.
Power-users are the ones that should have to deal with the options, and currently, they cannot switch off this feature.

Good point, agreed.
How about:

* a flag "--no-browser" that switches opening up a browser
* we add this flag to our cucumber feature definitions
* if your specs are affected by the "open with browser" feature we can stub it out there on a low level

WDYT?
*

**Comment by troessner** [comment]
OR we adjust the "--open" flag to allow for "--no-open" as well in Unix tradition. I think that would be confusing though since the "--open" form would take arguments while the "--no-open" form wouldn't.
So I'd probably rather go with "--no-browser".

**Comment by Onumis** [comment]
I agree on the "--no-browser" flag, keeping in mind that "--mode-ci" also does not open a browser.

**Comment by troessner** [comment]
Yeah, I had the "--mode-ci" flag in mind as well at first, but I'd rather prefer not to mix that up since it's also about running our test suite locally.

**Comment by superiorlu** [comment]
@Onumis @troessner  this is good idea. i will add this flag on a new branch.

**Comment by Onumis** [comment]
Fixed in #113

**Comment by Onumis** [comment]
Just want to share my frustration:
https://github.com/copiousfreetime/launchy/issues/51#issuecomment-176979526
