### ISSUE TITLE
Rubycritic throws errors with Ruby 2.3 syntax

### ISSUE THREAD

**Issue by seanhandley** [whitesmith/rubycritic#117]
This is due to this commit in the `ruby_parser` library not yet being released: https://github.com/seattlerb/ruby_parser/commit/da22d1e256305dff2bb549e9f13fcf9f69c43bb2

Flay and Flog both depend on an earlier version of `ruby_parser` that doesn't have support.

```ruby
# foo.rb
Object&.new
```

```
$ rubycritic
  foo.rb:1 :: parse error on value "." (tDOT)
  skipping foo.rb
running flay smells

running flog smells
ERROR: parsing ruby file foo.rb
Racc::ParseError: foo.rb:1 :: parse error on value "." (tDOT) at:
  /Users/sean/.rbenv/versions/2.3.0/lib/ruby/2.3.0/racc/parser.rb:528:in `on_error'
  /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ruby_parser-3.7.3/lib/ruby_parser_extras.rb:1125:in `on_error'
  /Users/sean/.rbenv/versions/2.3.0/lib/ruby/2.3.0/racc/parser.rb:259:in `_racc_do_parse_c'
  /Users/sean/.rbenv/versions/2.3.0/lib/ruby/2.3.0/racc/parser.rb:259:in `do_parse'
  /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ruby_parser-3.7.3/lib/ruby_parser_extras.rb:1037:in `block in process'
.
running reek smells
.
running complexity
ERROR: parsing ruby file foo.rb
Racc::ParseError: foo.rb:1 :: parse error on value "." (tDOT) at:
  /Users/sean/.rbenv/versions/2.3.0/lib/ruby/2.3.0/racc/parser.rb:528:in `on_error'
  /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ruby_parser-3.7.3/lib/ruby_parser_extras.rb:1125:in `on_error'
  /Users/sean/.rbenv/versions/2.3.0/lib/ruby/2.3.0/racc/parser.rb:259:in `_racc_do_parse_c'
  /Users/sean/.rbenv/versions/2.3.0/lib/ruby/2.3.0/racc/parser.rb:259:in `do_parse'
  /Users/sean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ruby_parser-3.7.3/lib/ruby_parser_extras.rb:1037:in `block in process'
.
running attributes
.
running churn
.
New critique at file:///Users/sean/src/foo/tmp/rubycritic/overview.html
Score: 100.0
```

**Comment by Onumis** [comment]
Thanks, we've had a long discussion about this (https://github.com/whitesmith/rubycritic/issues/81), eventually reaching the same conclusion.

I think ruby_parser still needs a few things to be done in order to ensure ruby 2.3 compatibility...

**Comment by troessner** [comment]
Yep, no idea when they will release though ... kind of sucks, cause currently RubyCritic is broken on 2.3. :(

**Comment by troessner** [comment]
I'll leave this issue around even though it's not a RubyCritic problem or a one that we can fix it all.
Probably other people will stumble across this as well.

**Comment by nijikon** [comment]
Is this still an issue with the current 2.7.1 release?

**Comment by troessner** [comment]
Unfortunately yes, since ruby_parser has still not seen a release for this. Meaning flay and flog are still broken in terms of proper ruby 2.3 support :-/

**Comment by troessner** [comment]
ruby_parser 3.8 [has been released](https://github.com/seattlerb/ruby_parser/commit/a966b2b7cf62567a34292561b7f00606e590a3bc) with Ruby 2.3. support
Both flay and flog should work now with Ruby 2.3.

Closing this one.

In case you still  have problems with this, try `bundle update ruby_parser` and if this doesn't help, please re-open this issue.

**Comment by seanhandley** [comment]
Awesome - thanks for the heads up @troessner
