### ISSUE TITLE
Undefined method `split' for nil:nilClass (NoMethodError)

### ISSUE THREAD

**Issue by midwire** [whitesmith/rubycritic#12]
I am getting the following error consistently when running rubycritic on a particular project:

```
.../gems/2.1.0/gems/rubycritic-1.1.0/lib/rubycritic/analysers/smells/flog.rb:48:in `smell_locations': undefined method `split' for nil:NilClass (NoMethodError)
```

I will dig further but wanted to submit this to see if anyone else has seen it.

**Comment by guilhermesimoes** [comment]
This has somewhat been fixed [upstream](https://github.com/seattlerb/flog/issues/49).

Given the following code:

```ruby
describe "Callback" do
  module LibTest
    extend FFI::Library
  end
end
```

Running `flog --all callback_spec.rb` yields:

```
1.0: describe#Bad                     callback_spec.rb:1
1.0: describe(Bad)::Helper#none
```

That `none` method does not exist and so obviously it's missing its file and line, which is far from ideal.

However, using Flog's option to skip code outside of methods, the `none` method is omitted.

Running `flog --all --methods-only callback_spec.rb` yields:

```
1.0: describe#Bad                     callback_spec.rb:1
```

And there you have it. Luckily, RubyCritic already uses this option so all Flog smells should have files and lines.

I consider this fixed for now, but if this type of error ever comes up again, please feel free to reopen.
