### ISSUE TITLE
Overall Score?

### ISSUE THREAD

**Issue by solars** [whitesmith/rubycritic#129]
Hi there, apologies I did not know where else I should ask so I'll try it here.

I know there is an issue about the explanation of the scores, but I could not find anything about the overall score in the overviews page - how is it calculated or what does it mean?

I want to use rubycritic in our CI, as a counterpart to sonarqube which is what our java guys use, it provides an overall score.
Also plato for javascript provides a maintainability index - is that overall score related?

Thanks a lot,
Christoph

**Comment by troessner** [comment]
I still haven't gotten around to document all-the-things unfortunately.

>> I know there is an issue about the explanation of the scores, but I could not find anything about the overall score in the overviews page - how is it calculated or what does it mean?

You mean the "A" "B" and so on or the gpa?
The gpa is explained in #35

**Comment by solars** [comment]
Thanks a lot for the pointer, it's called Score xx/100 in my version, so I was confused by the term GPA.

**Comment by Onumis** [comment]
I guess this has been answered already.
Updated metrics explanation: https://github.com/whitesmith/rubycritic/blob/master/docs/core-metrics.md
