### ISSUE TITLE
Missing status label (old/new)

### ISSUE THREAD

**Issue by nunosilva800** [whitesmith/rubycritic#146]
![RubyCritic smells index screenshot](http://i.imgur.com/PvkFEe3.png)

Latest version is not generating these "labels" on the rightmost columns.
Not sure when we lost this.

**Comment by vzamanillo** [comment]
I think is related to #115, with that changes the serialized dump will never exists, so there is nothing to compare.

**Comment by itsmeurbi** [comment]
I'd like to address this one
