### ISSUE TITLE
Move documentation into /docs to be under version control

### ISSUE THREAD

**Issue by Onumis** [whitesmith/rubycritic#147]
Context: https://github.com/whitesmith/rubycritic/issues/63#issuecomment-226925001

**Comment by troessner** [comment]
👍

**Comment by olleolleolle** [comment]
[Roadmap](https://github.com/whitesmith/rubycritic/wiki/Roadmap) is the only wiki page not yet in the docs/ folder.

Would you like it to be imported into the repository, in some form?

**Comment by Onumis** [comment]
Can't see any reason not to! :)

**Comment by olleolleolle** [comment]
@Onumis Let me prepare you a PR real quick. Idea: next to the `README.md` as `ROADMAP.md`.
