### ISSUE TITLE
Update rubocop to 0.41.1

### ISSUE THREAD

**Issue by rasaffieTP** [whitesmith/rubycritic#151]
It would be great to have access to the [new features](https://github.com/bbatsov/rubocop/releases/tag/v0.41.0).

| Ruby       | 2.3.1   |
| RubyCritic | 2.9.1   |

**Comment by troessner** [comment]
How about a PR? Should be a walk in the park ;)

**Comment by rasaffieTP** [comment]
:ok_hand: I will do it as soon as I can.

**Comment by nijikon** [comment]
#152

**Comment by nijikon** [comment]
@troessner This can be closed now, as we released 2.9.2.

**Comment by troessner** [comment]
Good point, thanks @nijikon :)
