### ISSUE TITLE
CI mode does not run only on the diff from master

### ISSUE THREAD

**Issue by thedrow** [whitesmith/rubycritic#161]
I don't really understand what rubycritic does when CI mode is on but it doesn't simply run on the files that have changed since the branching from master.
Is there a way to make rubycritic do so?

**Comment by thedrow** [comment]
```bash
DIFF_LIST=$(git diff --name-only $CIRCLE_SHA1 $(git merge-base $CIRCLE_SHA1 master) | grep .rb)
  if [ ! -z "$DIFF_LIST" ]; then
    bundle exec rubycritic --format console -m $DIFF_LIST
  else
    echo "No changes detected. Skipping rubycritic..."
  fi
```
does the trick on CircleCI. Maybe we should document this somehow?

**Comment by Onumis** [comment]
The CI mode runs only against the last commit. Doing it against the full diff of a branch is indeed very helpful. 
Gonna add this as a task.
Thanks for the CircleCI snippet, ideally, RubyCritic should handle that.

**Comment by thedrow** [comment]
I don't understand the difference between the CI mode and normal mode?
Are you able to visualize code quality over time?
