### ISSUE TITLE
UI/UX improvements for the current system

### ISSUE THREAD

**Issue by Aquil-Serene** [whitesmith/rubycritic#173]
Hi all,

I have been working on this for a while to give a nice, good looking facelift to **rubycritic**. Came to know about this from my colleagues and understood the workflows. Then I came with this solution. Please review it and feel free to give your valuable feedbacks.

Thanks,
Akhil.

![rc-home](https://cloud.githubusercontent.com/assets/22951879/19548847/80d82436-96be-11e6-92b9-667c683d7d50.png)
![rc-codes](https://cloud.githubusercontent.com/assets/22951879/19548856/8d714772-96be-11e6-903e-68d5d01d09e4.png)
![rc-code individual](https://cloud.githubusercontent.com/assets/22951879/19548861/93eb3bbc-96be-11e6-97e7-6c95da953573.png)
![rc-smells](https://cloud.githubusercontent.com/assets/22951879/19548873/a39faef8-96be-11e6-9b21-cf6791f4598d.png)
![rc-code individual -with-smells](https://cloud.githubusercontent.com/assets/22951879/19548874/a8653fb6-96be-11e6-9553-b089bb898f3d.png)

**Comment by troessner** [comment]
Oh, wow, I love it!
How about creating a pull request so we can discuss the changes you made in detail?

**Comment by Aquil-Serene** [comment]
Hi @troessner ,

It's just a design inspiration which I proposed. If we brainstorm on the images which I uploaded and finalizing the flow, we will get it developed and update.

**Comment by Onumis** [comment]
This is awesome! Thanks for all the effort!

**Comment by troessner** [comment]
I think its safe to say that we are all in favour :)

Lets get a pull reqest going!

**Comment by guilhermesimoes** [comment]
Oh, wow.

**Comment by Aquil-Serene** [comment]
I am having some shortage of resources and it will take some time if i wait to get someone to do this for me... If anyone is interested to help me with converting PSD to HTML, am happy to share the files... Please let me know if anyone out there...

**Comment by vijayanandnandam** [comment]
Hi All,
We are working on this issue
PSD to html conversion is underway. will revert back with a pr in couple of weeks.

**Comment by vijayanandnandam** [comment]
Hi All,
We are done with psd to html conversion and started working on integrating the new ui into rubycritic

**Comment by Onumis** [comment]
Awesome! I'm anxious to see that :smile:

**Comment by tejasbubane** [comment]
**Update:** We are very much done with the integration with minor JS/CSS fixes left. Expect PR in a day or two.

**Comment by tejasbubane** [comment]
PR: #184
