### ISSUE TITLE
gems/rubycritic-1.1.1/lib/rubycritic/source_control_systems/git.rb:31:in `count': invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by kvannotten** [whitesmith/rubycritic#18]
I get this error after installing + running it against a rails app.

|  | Version |
| --- | --- |
| Ruby | 2.1.2 |
| RubyCritic | 1.1.1 |

**Comment by jainankita90** [comment]
I am getting same error in docker env. I tried setting LANG variable in shell but no it does not fix the issue

rubycritic (3.2.2)
Rails 5.0.3
ruby 2.3.3p222
reek 4.6.2

**Comment by typhoon2099** [comment]
I'm getting the same issue in a docker image, setting `-e LANG=en_US.UTF-8` doesn't work. Using Ruby 2.5
