### ISSUE TITLE
Error occurs when no source control is used

### ISSUE THREAD

**Issue by Rataah** [whitesmith/rubycritic#188]
Hi,

I tried the new version on one of my project with no source control enabled and an error occurs:

```
O:/ruby/ruby-2.3.1-x64-mingw32/lib/ruby/gems/2.3.0/gems/rubycritic-3.1.0/lib/rubycritic/analysis_summary.rb:33:in `+': String can't be coerced into Fixnum (TypeError)
        from O:/ruby/ruby-2.3.1-x64-mingw32/lib/ruby/gems/2.3.0/gems/rubycritic-3.1.0/lib/rubycritic/analysis_summary.rb:33:in `block in churns'
        from O:/ruby/ruby-2.3.1-x64-mingw32/lib/ruby/gems/2.3.0/gems/rubycritic-3.1.0/lib/rubycritic/analysis_summary.rb:33:in `each'
```

The error is raised in the following method of AnalysisSummary class:
```ruby
    def churns
      modules.inject(0) { |acc, elem|
        acc + elem.churn 
      }
    end
```

Where the value of "**element.churn**" is the string "**N/A"**
The "**N/A**" value seems to come from the Double class in SourceControlSystem.
Precisely:
```ruby
      def revisions_count(_)
        'N/A'
      end
```

Ruby version: 
```
> ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]

```
Rubycritic version:
```
> gem list rubycritic

*** LOCAL GEMS ***

rubycritic (3.1.0)
```

Many thanks for this gem and keep up your excellent work!

**Comment by Onumis** [comment]
Thanks for the bug report!

**Comment by anlek** [comment]
I've hit the same bug. Any known workarounds?

Thanks

**Comment by icmonroe** [comment]
Hit the same issue. Anyone have a solution?

**Comment by troessner** [comment]
Replacing 'n/a' with 0 might work. No idea if this breaks something else :)
Pull requests welcome!

**Comment by troessner** [comment]
Ah, and a fix is up already :)
