### ISSUE TITLE
Running analysers multiple times

### ISSUE THREAD

**Issue by Linuus** [whitesmith/rubycritic#20]
Hi!

I really like this project so I wanted to contribute to it. I was going to start with something small, like: https://github.com/whitesmith/rubycritic/issues/3

I found that the analysers are run twice, once from the `Orchestrator` https://github.com/whitesmith/rubycritic/blob/master/lib/rubycritic/orchestrator.rb#L15 which in turn runs the `RevisionComparator` which runs the analysers again, https://github.com/whitesmith/rubycritic/blob/master/lib/rubycritic/revision_comparator.rb#L35

I'm just trying to understand the codebase a bit better before I start implementing stuff. Would you mind explaining what is going on a bit?

Cheers!

**Comment by guilhermesimoes** [comment]
I'm just closing for the sake of cleaning up, but feel free to continue the conversation!
