### ISSUE TITLE
Rake task is in module `Rubycritic` but rest of code is `RubyCritic` (case-sensitiive)

### ISSUE THREAD

**Issue by binkley** [whitesmith/rubycritic#213]
I noticed the rake task is in the module `Rubycritic` but the documentation and the rest of the code says `RubyCritic`.  Can this be easily changed so the rake task module uses the same case as the documentation and rest of code?

**Comment by olleolleolle** [comment]
I searched the repository for the `Rubycritic` term, and found only #157 - which is quite old. 

What version of the tool are you using to experience the above?

**Comment by itsmeurbi** [comment]
Currently(v4.7.0) there are no `Rubycritic` modules. I believe this issue can be closed
