### ISSUE TITLE
Code smells take up line numbers

### ISSUE THREAD

**Issue by mgrecar** [whitesmith/rubycritic#216]
Ruby Version: MRI 2.2.1p85
RubyCritic Version: 3.1.3

Code smells take up line numbers when viewing a Ruby file from the Code tab, like so:
![screen shot 2017-02-21 at 10 05 48 am](https://cloud.githubusercontent.com/assets/526181/23170739/54976cf8-f81e-11e6-9190-e2579854a407.png)

With files of any significant length, and more than a handful of smells, the line numbers quickly become far removed from the actual lines in the source code.  I don't believe the smells ought to count as lines.

**Comment by georgedrummond** [comment]
I'm seeing this too. I will try and write up a fix for it this weekend.
