### ISSUE TITLE
Feature Request: Consume SimpleCov and Use Results to Weigh Metrics

### ISSUE THREAD

**Issue by TreyE** [whitesmith/rubycritic#245]
It would be great if I could somehow also import simplecov results into rubycritic - and then as a result use those coverage values to help 'weigh' my metrics.  Basically I want lack of test coverage to act as something that magnifies how 'bad' I consider the code to be.

A simple case would be:

1. Prior to the application of the coverage metric, both classes A and B receive a the same rubycritic score
2. Class A has full test coverage
3. Class B has no test coverage
4. Class A should either receive an improved rating or keep it's current rating.
5. Class B should receive a far worse rating that it would have prior to the code coverage metric being factored.

**Comment by Onumis** [comment]
@TreyE alright so the flow would be:

- run your test suite(s) with codecov
- run rubycritic passing in the codecov `.resultset.json`
    - for each examined file, look up the code coverage results for that file
    - assign a score based on it, which will affect the final rating

Although I don't think we should mix code quality with test coverage, perhaps this is useful for somebody.
Want to get started with a PR? :D

**Comment by gonzaloaune** [comment]
👍

**Comment by joshsaintjacque** [comment]
@TreyE Is this something you're working on? If not, I'd love to make a PR.

**Comment by TreyE** [comment]
Nope, nothing I've been working on - just something I hope somebody picks up.

**Comment by etagwerker** [comment]
@Onumis @TreyE @joshsaintjacque I really like this idea. I like it so much that I submitted a PR for it: #319 

I'd really like to know your feedback about those changes. 

Coverage and quality data are not mixed nor combined. Coverage data now shows up in a new section. 

There is no need to pass in the coverage folder or `.resultset.json`, the changes I propose use SimpleCov's configuration to find that file. 😸

**Comment by etagwerker** [comment]
In case you are interested in this feature, I recently release [`skunk`](https://github.com/fastruby/skunk) which uses `rubycritic` and `simplecov` to calculate **one metric** called the "StinkScore" 

I wrote a blog post about this: https://www.fastruby.io/blog/code-quality/intruducing-skunk-stink-score-calculator.html 😃
