### ISSUE TITLE
Ignore symlinks

### ISSUE THREAD

**Issue by LeeXGreen** [whitesmith/rubycritic#25]
Hi,

I've been running RubyCritic on a large Rails project. We use Rails engines to organize / separate our code, and for better or worse, we have a number of symlinked files from one engine to another or back to the main app. (I'd like to remove these links eventually but that's another discussion.)

When we run RubyCritic on this project, we get a lot of duplicate code warnings, and the source/target of the duplication are the source/target of the symlinks. It would be nice if RubyCritic could be configured to ignore symlinks.

I know that my use case might not be very common, so I'm prepared to work on this myself. I just wanted to open an issue here to answer a few questions:

* is this something that should be implemented at the RubyCritic level?
  * I think so, given the SourceLocator class
* should RubyCritic just ignore symlinks by default?
  * if not, should this be a CLI option?

Note -- this is RubyCritic version 1.1.1 running under JRuby 1.7.9 (which implements Ruby 1.9.3)

**Comment by guilhermesimoes** [comment]
I am sensible of your problem and your proposed solution looks good to me.

Regarding your questions:

> is this something that should be implemented at the RubyCritic level?
> * I think so, given the SourceLocator class

I think so too. But I'm surprised this issue hasn't come up before in more well known gems such as RuboCop or Reek.

> should RubyCritic just ignore symlinks by default?
> * if not, should this be a CLI option?

I'm torn on this. I think it definitely should ignore a symlink if it points to a file that will be also included. However, if it points to a file outside of the current directory tree then it shouldn't be ignored.

For now, making this a CLI option (turned off by default) is a good compromise and (most importantly) backwards compatible.

Also, good to know that RubyCritic is running well under JRuby :smile:

**Comment by guilhermesimoes** [comment]
Closed by #26 :clap:
