### ISSUE TITLE
Solve Rubocop warnings

### ISSUE THREAD

**Issue by nunosilva800** [whitesmith/rubycritic#250]
Go through `.rubocop_todo.yml` and fix those issues :) 

Just remove a line, run `rubocop` and you should see the warning/error.

**Comment by zhikiri** [comment]
@Onumis I'll check it out

**Comment by ericboehs** [comment]
I'll run the auto correct for `SpecialGlobalVars`.

**Comment by zhikiri** [comment]
@ericboehs you can do everything, I'm really busy now

**Comment by Onumis** [comment]
@tibbon if you are using latest rubocop, then we need to update the `AllCops/Include` setting in `.rubocop.yml` file

See https://github.com/bbatsov/rubocop/issues/4247#issuecomment-389364734
