### ISSUE TITLE
Impossible to install Rubycritic on Windows for restricted users

### ISSUE THREAD

**Issue by Rataah** [whitesmith/rubycritic#257]
Hi,
I have to use Windows with a restricted user account. 
Install Rubycritic is impossible due to a symbolic link in the sample directory of the gem.

```
> gem install rubycritic
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_file_s_symlink - (test/samples/location/file0.rb, C:/work/RISF/ruby/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rubycritic-3.3.0/test/samples/location/file0_symlink.rb)
```

Ruby version:
```
> ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
```

rubycritic version:
3.3.0

**Comment by SuperSandro2000** [comment]
To fix that it would be necessary to skip that test on Windows or use an link file. Don't think both solutions are ideal.

**Comment by leobenkel** [comment]
any news about that ?

**Comment by dbwest** [comment]
bump. this is a big problem for all our testers...

**Comment by makpark** [comment]
Download the gem to the machine and From an elevated or Administrator Cmd window, navigate to the download path and try gem install "filename"

**Comment by Onumis** [comment]
Will attempt something like this: https://github.com/DatabaseCleaner/database_cleaner/issues/506

**Comment by Onumis** [comment]
Here it is: https://rubygems.org/gems/rubycritic/versions/3.5.0
thanks everyone :v:
