### ISSUE TITLE
General Styling, GPA

### ISSUE THREAD

**Issue by drewbailey** [whitesmith/rubycritic#27]
I recently started using this gem and was looking for a project to start contributing to and thought this would be a good choice! 

From quickly looking over some of the codebase I thought adding an overall GPA indicator and some new styling would be a good place to start and wanted to see what your thoughts were?

**Comment by guilhermesimoes** [comment]
Thanks for thinking of contributing! Any and all contributions are welcome.

Regarding the UI, scroll down to the bottom of this "[roadmap][1]" for a few ideas on where it could be heading.

If you get stuck inside the codebase, feel free to use this issue to ask questions. I've said in the past that I would add comments to the codebase but I still haven't gotten around to that. Maybe one of these weekends...

[1]: https://github.com/whitesmith/rubycritic/wiki/Roadmap
