### ISSUE TITLE
Add indicator that the gem is running

### ISSUE THREAD

**Issue by guilhermesimoes** [whitesmith/rubycritic#3]
In sizeable apps, it can take up to 20 seconds to generate the first report. Rubycritic should show a progress bar to keep the user happy :)

Gem candidates:

* https://github.com/jfelchner/ruby-progressbar

* https://github.com/thekompanee/fuubar

* https://github.com/paul/progress_bar

**Comment by LeeXGreen** [comment]
Just a helpful note here: as of rubocop 0.28.0, it depends on ruby-progressbar so that might be a good choice.

**Comment by guilhermesimoes** [comment]
That's a very good point. I'm quite confident that the next library to be integrated into RubyCritic will be RuboCop so having overlapping dependencies would be great.

Also, the RuboCop guys definitely know what they're doing so if they picked ruby-progressbar then it's because it's the best option.

**Comment by natesholland** [comment]
I think we could tie this in at `AnalysersRunner#run` inside the `ANALYSERS.each` loop, or at the more granular level inside each Analyzer in their run method.

**Comment by Linuus** [comment]
Hi!

I just remembered that I actually experimented with this in rubycritic a long time ago. It uses ruby-progressbar

Example:
![skarmavbild 2015-04-27 kl 16 55 47](https://cloud.githubusercontent.com/assets/379823/7350242/71cbb5fe-ecfe-11e4-8ea7-03078730e88a.png)

Is that enough or do we want an even more granular progress bar? Maybe it just adds noise... :)

Interested?

**Comment by natesholland** [comment]
I know we definitely want a progress bar. I took at a pass at it here: https://github.com/whitesmith/rubycritic/pull/36 but I don't think it could hurt to have two different takes on it.

**Comment by Linuus** [comment]
Oh, right. I didn't  see that PR :)

@guilhermesimoes Any thoughts?

**Comment by troessner** [comment]
#36 has been merged, closing this one.
