### ISSUE TITLE
--suppress-ratings breaks HTML output

### ISSUE THREAD

**Issue by cvoltz** [whitesmith/rubycritic#304]
Running rubycritic with the `--suppress-ratings` option results in a misaligned report for the code:

![Screenshot from 2019-03-21 15-21-08](https://user-images.githubusercontent.com/549284/54782615-506a8000-4bed-11e9-8766-4134c9061b69.png)

**Comment by jbampton** [comment]
I think #302  fixed this.

**Comment by cvoltz** [comment]
Confirmed that #302 did fix the problem with the `Name` showing up in the `Churn` column but the alignment for the `Churn` column is wrong. That column is now `text-align: left` instead of `text-align: right` like it is in the case where `--suppress-ratings` is not specified.

#### Without the ratings suppressed
![Without the ratings suppressed](https://user-images.githubusercontent.com/549284/57143659-f381ee00-6d84-11e9-9d18-2b9b352a937e.png)

#### With the ratings suppressed
![With the ratings suppressed](https://user-images.githubusercontent.com/549284/57143694-10b6bc80-6d85-11e9-897d-b80825d09777.png)

Looks like `lib/rubycritic/generators/html/assets/stylesheets/application.css` needs to be updated. Right now it has:
```
/*TD*/
.table td {
  color: #777575;
}
.table.code td:nth-child(1) {
  text-align: center;
}
.table.code td:nth-child(2) {
  text-align: left;
}
.table.code td {
  text-align: right;
}
```
So `text-align` is fixed to the column number. Since what is in a given column changes based on the setting of `--suppress-ratings`, the CSS needs to be changed too. I would suggest just adding a class attribute in the HTML for each column and then specify the desired layout in the CSS file using the class name rather then using `td:nth-child`.
