### ISSUE TITLE
Backticks are breaking Rubycritic

### ISSUE THREAD

**Issue by lflucasferreira** [whitesmith/rubycritic#318]
Version: 4.1.0

I have a method as follows:
def start
    `#{executable}`
end

The "executable" is a method that instantiates a class in order to get the executable file path. For some reason, rubycritic is not working. I tested with another method using a different command and it processed as supposed to. Very strange.

When I run Rubycritic it fails and throws this error:

running flay smells

running flog smells
.........Traceback (most recent call last):
        48: from C:/Ruby25-x64/bin/rubycritic:23:in `<main>'
        47: from C:/Ruby25-x64/bin/rubycritic:23:in `load'
        46: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubycritic-4.1.0/bin/rubycritic:10:in `<top (required)>'
        45: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubycritic-4.1.0/lib/rubycritic/cli/application.rb:21:in `execute'
        44: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubycritic-4.1.0/lib/rubycritic/commands/default.rb:19:in `execute'
        43: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubycritic-4.1.0/lib/rubycritic/commands/default.rb:24:in `critique'
        42: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubycritic-4.1.0/lib/rubycritic/analysers_runner.rb:27:in `run'
        41: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubycritic-4.1.0/lib/rubycritic/analysers_runner.rb:27:in `each'
        40: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubycritic-4.1.0/lib/rubycritic/analysers_runner.rb:30:in `block in run'
        39: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubycritic-4.1.0/lib/rubycritic/analysers/smells/flog.rb:20:in `run'
        38: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubycritic-4.1.0/lib/rubycritic/core/analysed_modules_collection.rb:32:in `each'
        37: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubycritic-4.1.0/lib/rubycritic/core/analysed_modules_collection.rb:32:in `each'
        36: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubycritic-4.1.0/lib/rubycritic/analysers/smells/flog.rb:21:in `block in run'
        35: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rubycritic-4.1.0/lib/rubycritic/analysers/smells/flog.rb:35:in `add_smells_to'
        34: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/flog-4.6.3/lib/flog.rb:177:in `flog'
        33: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/flog-4.6.3/lib/flog.rb:177:in `each'
        32: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/flog-4.6.3/lib/flog.rb:182:in `block in flog'
        31: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/flog-4.6.3/lib/flog.rb:194:in `flog_ruby'
        30: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/flog-4.6.3/lib/flog.rb:229:in `flog_ruby!'
        29: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:245:in `process'
        28: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:388:in `in_context'
        27: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:268:in `block in process'
        26: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:324:in `error_handler'
        25: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:269:in `block (2 levels) in process'
        24: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/flog-4.6.3/lib/flog.rb:356:in `process_block'
        23: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/flog-4.6.3/lib/flog.rb:267:in `penalize_by'
        22: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/flog-4.6.3/lib/flog.rb:357:in `block in process_block'
        21: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:692:in `process_until_empty'
        20: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:245:in `process'
        19: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:388:in `in_context'
        18: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:268:in `block in process'
        17: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:324:in `error_handler'
        16: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:269:in `block (2 levels) in process'
        15: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/flog-4.6.3/lib/flog.rb:415:in `process_class'
        14: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:605:in `process_class'
        13: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:538:in `in_klass'
        12: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:710:in `with_new_method_stack'
        11: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:539:in `block in in_klass'
        10: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:607:in `block in process_class'
         9: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/flog-4.6.3/lib/flog.rb:419:in `block in process_class'
         8: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:692:in `process_until_empty'
         7: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:245:in `process'
         6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:388:in `in_context'
         5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:268:in `block in process'
         4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:324:in `error_handler'
         3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:269:in `block (2 levels) in process'
         2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp_processor.rb:624:in `process_defn'
         1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp.rb:234:in `line_max'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/sexp_processor-4.13.0/lib/sexp.rb:234:in `max': comparison of NilClass with 27 failed (ArgumentError)

**Comment by lflucasferreira** [comment]
You can reproduce that using the following:

def test
    'Test'
  end

  def bug
    `#{test}`
  end

**Comment by Onumis** [comment]
What happens if you run `flog` alone on that file? 
The stacktrace seems to tell that it is an issue in Flog (a dependency of Rubycritic.

**Comment by lflucasferreira** [comment]
I have the same output.
I decided to use another way: 
> system(executable)

**Comment by Onumis** [comment]
It does seem like an issue within `flog` itself. Mind opening an issue there? https://github.com/seattlerb/flog
