### ISSUE TITLE
Flay | How to disable it or exclude some files from its analysis?

### ISSUE THREAD

**Issue by lflucasferreira** [whitesmith/rubycritic#321]
Hi,

The Flay is pointing a DuplicateCode Smell in two files. I would like to ignore these files and increase the code score, but there is no documentation about how to disable/exclude this smell.

Could you please help me? I'm lost.

**Comment by Yinfei** [comment]
Hello 👋 

I tried introducing a `.flayignore` file but it seems that it's ignore by rubycritic itself. 🤔 

Is there any way that rubycritic could take this into account?

**Comment by mvz** [comment]
@Yinfei sorry, I'm not very familiar with how rubycritic works. I only work on the Reek project.

**Comment by lflucasferreira** [comment]
> Hello 👋
> 
> I tried introducing a `.flayignore` file but it seems that it's ignore by rubycritic itself. 🤔
> 
> @mvz Is there any way that rubycritic could take this into account?

Could you please tell me how to configure the `.flyignore?` file? TYIA.

**Comment by mvz** [comment]
I also don't know anything about Flay, which is a separate project.
