### ISSUE TITLE
RubyCritic v4.2.0: Color coding of files in Coverage section is off

### ISSUE THREAD

**Issue by etagwerker** [whitesmith/rubycritic#324]
Hey all, 

I noticed that my implementation of SimpleCov for RubyCritic has a minor flaw. Color coding is not working as one would expect.

In this scenario, files with D and F code coverage grades should show up with a different color: 

<img width="1260" alt="Screen Shot 2019-10-28 at 2 08 19 PM" src="https://user-images.githubusercontent.com/17584/67705186-e852f800-f98c-11e9-9702-d851ff4f810d.png">

I can take a stab at fixing this, so that it follows the same logic as the color coding related to "cost" of a module.

**Comment by Onumis** [comment]
Thanks, released in v4.2.1
