### ISSUE TITLE
Dependency conflict with simplecov

### ISSUE THREAD

**Issue by n-rodriguez** [whitesmith/rubycritic#344]
Hi there!

It seems there's a dependency conflict with `simplecov` gem :

```sh
Bundler could not find compatible versions for gem "simplecov":
  In gems.rb:
    simplecov (= 0.18.0)

    rubycritic (= 4.3.2) was resolved to 4.3.2, which depends on
      simplecov (~> 0.17.0)
```
Thank you!

**Comment by etagwerker** [comment]
@n-rodriguez Thanks for reporting this! 

I think we might need to relax the dependency on `simplecov`: 

https://github.com/whitesmith/rubycritic/blob/master/rubycritic.gemspec#L40

Maybe we need to change that line to be: 

```
  spec.add_runtime_dependency 'simplecov', '>= 0.17.0'
```

**Comment by etagwerker** [comment]
@n-rodriguez You might want to try https://github.com/whitesmith/rubycritic/tree/fix-deprecations which relaxes the dependency declaration for `simplecov`

**Comment by n-rodriguez** [comment]
I've tested with https://github.com/fastruby/rubycritic/tree/fixes/relax-simplecov-dep and it works :+1:

**Comment by n-rodriguez** [comment]
https://github.com/whitesmith/rubycritic/tree/fix-deprecations : 
> This branch is 1 commit ahead, 61 commits behind master.

**Comment by etagwerker** [comment]
@n-rodriguez Could you check with the new release and close this issue if this is solved? 😄

**Comment by n-rodriguez** [comment]
@etagwerker it works! thank you!
