### ISSUE TITLE
RubyCritic Pipeline

### ISSUE THREAD

**Issue by teekenl** [whitesmith/rubycritic#368]
Was rubycritic supported to be included into Gitlab Pipeline, says, if i want to include this code quality metric tool whenver someone push new changes into a PR?

**Comment by nunosilva800** [comment]
It should support that flow, very much like it supports jenkins (see the (docs)[https://github.com/whitesmith/rubycritic/tree/master/docs]) and circleCI (see this (demo)[https://github.com/nunosilva800/rubycritic-ci-demo/blob/master/.circleci/config.yml]).

It would be great to have docs/guides on the steps to set these up in Gitlab Pipeline and/or GH actions 😉

**Comment by etagwerker** [comment]
@teekenl I'm not familiar with the Gitlab Pipeline, but you could easily set up a GitHub action like this: https://github.com/fastruby/skunk/blob/main/.github/workflows/skunk.yml

In that example I'm using `skunk` which is very similar to `rubycritic`

The main steps would be: 

1. Install rubycritic
2. Run rubycritic

Bonus points: You can easily detect whether you are running `rubycritic` in the main branch or in a feature/patch branch, so then you can use the command with `-b` to compare the changes with the main branch. 

I hope this helps!
