### ISSUE TITLE
[ASK] DuplicateCode problem

### ISSUE THREAD

**Issue by jellythomas** [whitesmith/rubycritic#375]
Hello guys, i've a question how the DuplicateCode works, i've this line of code thats read as DuplicateCode:

job_positions_controller.rb
job_position = JobPosition.new

job_levels_controller.rb
job_level = JobLevel.new

i dont really get on how the rubycritic scan the duplicatecode, can anyone give me a hint? tq in advance

**Comment by etagwerker** [comment]
@jellythomas Could you please provide more details? RubyCritic uses a few tools so this is probably coming from Reek?

**Comment by jellythomas** [comment]
> @jellythomas Could you please provide more details? RubyCritic uses a few tools so this is probably coming from Reek?

my bad this is the result of the rubycritic that i run

<img width="416" alt="Screen Shot 2020-12-08 at 21 49 25" src="https://user-images.githubusercontent.com/43949871/101499089-6f9bd900-399f-11eb-92ba-70f61d307ca4.png">

<img width="341" alt="Screen Shot 2020-12-08 at 21 49 33" src="https://user-images.githubusercontent.com/43949871/101499103-73c7f680-399f-11eb-8aa5-4fc32dcf4e3f.png">

**Comment by etagwerker** [comment]
@jellythomas This sounds like a question for `flay` -- I'm not sure about its implementation. 

You could ignore that file entirely with a `.flayignore` file, but that might be a little too much for this: https://github.com/seattlerb/flay#featuresproblems- 

Personally I wouldn't worry too much about this issue and I would ignore it, trying to focus on other more important issues. But that is only my opinion.

**Comment by jellythomas** [comment]
> @jellythomas This sounds like a question for `flay` -- I'm not sure about its implementation.
> 
> You could ignore that file entirely with a `.flayignore` file, but that might be a little too much for this: https://github.com/seattlerb/flay#featuresproblems-
> 
> Personally I wouldn't worry too much about this issue and I would ignore it, trying to focus on other more important issues. But that is only my opinion.

hoo okay got it, tq for your response, i'll try to ask on flay side, @etagwerker
