### ISSUE TITLE
analyzer modules run twice after previous run errored

### ISSUE THREAD

**Issue by natesholland** [whitesmith/rubycritic#38]
I'm not completely sure why this is happening but it seems as though if I use `ctrl-c` to exit out of a run, the next time I run rubycritic it runs the whole suite twice.

**Comment by guilhermesimoes** [comment]
RubyCritic always runs twice for a certain commit. This way we can compare changed code with committed code so we can tell which smells were recently introduced (before they are committed). After running the first time, we save the commit analysis in a file so we don't have to analyse that commit again.

There's a `--mode-ci` which you can use to skip this behaviour.
