### ISSUE TITLE
SimpleCov coverage_dir in non-standard location

### ISSUE THREAD

**Issue by typhoon2099** [whitesmith/rubycritic#390]
I have a project which uses a number of reporting tools, which we've subdirectoried under coverage. As such we've moved the SimpleCov results to `coverage/rspec`. Can rubycritic be configured to look there for the `.resultset.json` and `.resultset.json.lock` files?

**Comment by etagwerker** [comment]
@typhoon2099 Yes, I believe it _should work_ as long as `SimpleCov.coverage_path` resolves to the right directory: 

https://github.com/whitesmith/rubycritic/blob/main/lib/rubycritic/analysers/coverage.rb#L50-L52

When you run RubyCritic, do you see any data in the coverage section?

**Comment by typhoon2099** [comment]
No, I don't. The coverage directory is set in a Rails initializer, it's not something that's global as far as I'm aware, or at  the very least rubycritic is running it out of context. Is this something I can resolve by setting it up as a rake task?

**Comment by etagwerker** [comment]
@typhoon2099 Not sure what is the best way to do this, but you could try adding a one-liner to your `Rakefile` to make sure that the coverage_path is set before running the RubyCritic rake task: https://github.com/whitesmith/rubycritic#rake-task

**Comment by typhoon2099** [comment]
There's a simpler solution! https://github.com/simplecov-ruby/simplecov#using-simplecov-for-centralized-config

I've moved the config out of the Rails initializer and into `.simplecov` and the coverage gets picked up fine.

**Comment by typhoon2099** [comment]
I know I've closed this but it does appear that `.resultset.json` is getting overwritten when `rubycritic` is run. I'm guessing that since it's loaded in then it starts checking the coverage of `rubycritic` itself...

**Comment by etagwerker** [comment]
@typhoon2099 hm.. That's very weird, could you please create another issue for that? As far as I can remember, we are not writing anything to `.resultset.json`, we are only reading what is there to calculate coverage metrics. Thanks!

**Comment by typhoon2099** [comment]
I've raised #391 to discuss it.
