### ISSUE TITLE
Drop support for Ruby 2.5.x

### ISSUE THREAD

**Issue by nunosilva800** [whitesmith/rubycritic#409]
Akin to https://github.com/whitesmith/rubycritic/issues/406

- [ ] Drop ruby 2.5.x from test suite config -- Stop running the test suite with ruby 2.5
- [ ] Update README to point users in the right direction so they can figure out if their ruby version is supported
- [ ] Add required_ruby_version to the gemspec file and make it >= 2.6

**Comment by cleicar** [comment]
@nunosilva800 thanks for adding this issue, I'll send a PR later today
