### ISSUE TITLE
Document supported ruby versions/integrate Travis for those versions

### ISSUE THREAD

**Issue by bglusman** [whitesmith/rubycritic#42]
As I mentioned in #37, upgrading rubycritic broke debt_ceiling, because I support/test against 1.9, JRuby (1.9 mode), 2.x and RBX, and 1.4 introduced Hash#to_h usage, which isn't supported in 1.9.  So while I'd like this fixed, if you want to support 1.9, I realize 1.9 is now officially deprecated and maybe the real fix is to just make explicit what you support and perhaps add Travis for each of those environments.

**Comment by guilhermesimoes** [comment]
Every Ruby specified in the Travis config is supposed to be supported. Even though people should upgrade, [a lot of them are still on 1.9](https://semaphoreci.com/blog/2014/08/27/ruby-version-usage-in-commercial-projects-2014-edition.html).

I didn't realize `to_h` broke 1.9, I'm going to fix that.

**Comment by guilhermesimoes** [comment]
So I tried running RubyCritic on 1.9 and everything worked fine. What is it exactly that is breaking in your case? Can you provide a stack trace?

**Comment by bglusman** [comment]
@guilhermesimoes sure! Easiest repro is checking out debt_ceiling on one of the updated branches, use  a 1.9 ruby (I did this with ` rvm use 1.9.3-p362`) and removing `lib/debt_ceiling/compatibility.rb` and the require line in `lib/debt_ceiling.rb` and run the test suite, or just run the binary on debt ceiling itself (`bin/debt_ceiling`) If you clone the repo this branch will work: 
`git co upgrade_candidate_with_slow_rubycritic`

Anyway the stack trace from running binary is this:
```
/Users/brian/.rvm/gems/ruby-1.9.3-p362/gems/rubycritic-1.4.0/lib/rubycritic.rb:5:in `create': undefined method `to_h' for {:mode=>:ci, :format=>:json, :paths=>["."]}:Hash (NoMethodError)
	from /Users/brian/projects/debt_ceiling/lib/debt_ceiling/accounting.rb:38:in `construct_rubycritic_modules'
	from /Users/brian/projects/debt_ceiling/lib/debt_ceiling/accounting.rb:10:in `calculate'
	from /Users/brian/projects/debt_ceiling/lib/debt_ceiling.rb:37:in `calculate'
	from bin/debt_ceiling:3:in `<main>'
```
