### ISSUE TITLE
Add support for Ruby 3.2

### ISSUE THREAD

**Issue by go2null** [whitesmith/rubycritic#429]
Currently, RubyCritic only supports up to Ruby 3.1.  Ruby 3.2 was released last month.

**Comment by mhenrixon** [comment]
Is that why I get the following issue on CI?

<img width="1285" alt="CleanShot 2023-03-22 at 10 50 53@2x" src="https://user-images.githubusercontent.com/106795/226866052-7f890071-ab08-4f21-b032-53cd453916d1.png">

**Comment by etagwerker** [comment]
@go2null Have you seen any failures with Ruby 3.2? I just ran the test suite for RubyCritic locally with Ruby 3.2 and everything seems to be fine. 

> 155 runs, 258 assertions, 0 failures, 0 errors, 0 skips
> Coverage report generated for Unit Tests to 
> /Users/etagwerker/Projects/fastruby/rubycritic/test/samples/coverage_sample/0.21. 2453 / 2530 LOC (96.96%) covered.
