### ISSUE TITLE
Rubycritic support for Ruby 3.2.2

### ISSUE THREAD

**Issue by joaoleal93** [whitesmith/rubycritic#462]

**Comment by faisal** [comment]
What is the issue here?

**Comment by joaoleal93** [comment]
Hi, i am having a problem using ruby critic for ruby version 3.2.2

<img width="1439" alt="image" src="https://github.com/whitesmith/rubycritic/assets/120674699/7a420264-28d7-4a6f-89d9-9cf4859148fc">

**Comment by fbuys** [comment]
I'll take a look at this one.

**Comment by fbuys** [comment]
I have added a PR for this request: https://github.com/whitesmith/rubycritic/pull/467
