### ISSUE TITLE
Rubycritic Gem installation Failed

### ISSUE THREAD

**Issue by abhikanojia** [whitesmith/rubycritic#477]
Rubycritic gem installation is failing.
Upon investigating further I found that it is due to reek version got updated recently

https://rubygems.org/gems/reek 

Reek is now at 6.2.0 unlike 6.1.4 where it used to work fine.

<img width="1347" alt="image" src="https://github.com/whitesmith/rubycritic/assets/31365275/50ab324c-5cd8-4bc1-a119-76cf7dc85467">

**Comment by nunosilva800** [comment]
The [gemspec for reek is](https://github.com/whitesmith/rubycritic/blob/v4.7.0/rubycritic.gemspec#L38) `'~> 6.0', '< 7.0'`.
You should be able to set you gemfile to `gem reek, '< 6.2'` and get a successful installation. 

The only other thing we might want to do is to push a patch for version 4.7.1 that constrains reek version and/or further restricks `required_ruby_version `.

Of course the best thing you can do is to upgrade the ruby installation to a version that is still maintained.

**Comment by etagwerker** [comment]
This works for me with this version: rubycritic-4.9.0

At the same time I think it'd be a good idea to drop support for Ruby 2.7 and follow reek's lead on requiring Ruby 3.0 or higher. We can continue that conversation over here: https://github.com/whitesmith/rubycritic/issues/482
