### ISSUE TITLE
Discontinued 'virtus' dependency

### ISSUE THREAD

**Issue by Rishabhs343** [whitesmith/rubycritic#495]
The virtus gem, a dependency of rubycritic(https://github.com/whitesmith/rubycritic/blob/main/rubycritic.gemspec#L43C32-L43C38), has been discontinued and last updated on June 7, 2021. Are there any plans to remove or replace it with an actively maintained alternative?

**Comment by etagwerker** [comment]
@Rishabhs343 Thanks for bringing this up. There are no plans to remove or replace this dependency.

If you are (or anyone is) interested in replacing it with https://dry-rb.org/gems/dry-types/1.2/ I think that would be a good idea.

**Comment by Rishabhs343** [comment]
@etagwerker Thank you for the clarification. Since there are no plans to remove or replace this dependency, I'll go ahead and close this issue. However, I'm interested in exploring the replacement with [dry-types](https://dry-rb.org/gems/dry-types/1.2/). I'll look into it and see what can be done.
