### ISSUE TITLE
Improving (?) interface

### ISSUE THREAD

**Issue by Linuus** [whitesmith/rubycritic#54]
Hi!

I experimented a little bit the other day improving on the interface. Before I go any further I'd just like to see what you think about it. :) I haven't done that much yet and I'm definitely no designer. I've mostly worked on the code file page.

It is based off of  Bootswatch Sandstone [Link](https://bootswatch.com/sandstone/).

Anyways... Here are some gifs.

Gif 1
![screen1](https://cloud.githubusercontent.com/assets/379823/7387010/ddb5c9d8-ee59-11e4-9f1d-971f994cc040.gif)

Gif 2
![screen2](https://cloud.githubusercontent.com/assets/379823/7387011/ddb8a7e8-ee59-11e4-936e-3a1e21440a52.gif)

Thoughts?

**Comment by Linuus** [comment]
Ping @guilhermesimoes

**Comment by doomspork** [comment]
I like the new code page :+1:

**Comment by marceloboth** [comment]
Good job @Linuus :+1:
