### ISSUE TITLE
Expose Reek parameters attribute

### ISSUE THREAD

**Issue by lucasmazza** [whitesmith/rubycritic#57]
Reek `SmellWarning` class has a `parameters` Hash that contains more details about each smell, like the number of external references on a `FeatureEnvy` smell, which could be useful to identify which smells are bigger than others. Would be interesting to expose this information somehow through Rubycritic so end users can know more about the smells that were detected by reek.

Would make sense to have a `Hash` of custom attributes in the `Smell` class to expose this? I would be glad to send a PR with this later.

**Comment by troessner** [comment]
We recently revamped SmellWarning significantly https://github.com/troessner/reek/blob/master/lib/reek/smells/smell_warning.rb#L17 - should be easier to use it now. Pull request welcome!

**Comment by troessner** [comment]
Not much has happened here in half a year - closing this one.
