### ISSUE TITLE
reek 3 has been released

### ISSUE THREAD

**Issue by troessner** [whitesmith/rubycritic#58]
reek 3 has been released: https://troessner.wordpress.com/2015/07/04/reek-3-has-been-released/
and one of the biggest feature is a stable, simple API: https://github.com/troessner/reek/blob/master/docs/API.md
Since rubycritic uses a pretty old version of reek (2.0.4 with the current being 3.0.3) I think it would be great if you could upgrade to the latest version.
Not to mention that we fixed quite a few annoying bugs.:)

**Comment by nijikon** [comment]
Can we at least create a new version that has the reek 2.x dependency?

**Comment by nijikon** [comment]
ping

**Comment by troessner** [comment]
@nijikon I guess you have to look into this yourself I'm afraid :(
If you come up with a preliminary pull request pointing at this repo I'd try to help you where I can though ;)

**Comment by troessner** [comment]
We're on 3.6 now, closing this.

**Comment by nijikon** [comment]
@troessner awesome, just updated to 2.1.0 :heart:
