### ISSUE TITLE
Code view Filter/Search

### ISSUE THREAD

**Issue by jbodah** [whitesmith/rubycritic#60]
While I can just `cmd + f` for the things I'm interested in, it would be great to be able to filter the "Code" view results by a keyword. This way I can quickly check all of the modules under a certain namespace that I'm working on for flaws

**Comment by troessner** [comment]
>> While I can just cmd + f for the things I'm interested in, it would be great to be able to filter the "Code" view results by a keyword. 

I have zero idea what you're referring to :)
What editor? What does "Code view" mean?

**Comment by Onumis** [comment]
I think he is referring to the report (the html version, most likely).

There are a lot of things to be improved in displaying the reports to improve UX but I don't think that's anywhere near a priority at the moment. Nevertheless contributions are more than welcome!

**Comment by jbodah** [comment]
Sorry I meant the `code_index` view. It would be convenient to have some sort of filtering of that list (it's a minor nuisance when running rubycritic on our entire legacy app codebase). Just would like to put it here for documentation

**Comment by penkz** [comment]
What about using something like data tables? It's I guess it's simple enough, and it works great for filtering data in a table on the client side

https://www.datatables.net/
