### ISSUE TITLE
Document Ratings 

### ISSUE THREAD

**Issue by bparanj** [whitesmith/rubycritic#63]
What are the different ratings? What do they mean? It's not clear from the code or documentation what the desired ratings should be.

**Comment by guilhermesimoes** [comment]
It's on [the roadmap™](https://github.com/whitesmith/rubycritic/wiki/Roadmap).

Still, [this should help](https://gist.github.com/brynary/21369b5892525e1bd102).

**Comment by troessner** [comment]
Legit questions ;)
We really should document and / or define that.
I'll look into preparing a discussion.

**Comment by Onumis** [comment]
Proposal for this:
https://gist.github.com/Onumis/dfcfd98267041ebdff02

**Comment by Onumis** [comment]
Added a wiki page with the proposed docs.

**Comment by troessner** [comment]
Not the biggest fan of the github wiki - what do you think about integrating this into our README?

**Comment by Onumis** [comment]
Well, I was thinking of dropping a mention there (and possibly move some sections into wiki pages).
I'm not a big fan of huge a README :P

**Comment by troessner** [comment]
I can see your reservations, I have the similar feelings towards big README.
But take a look at the [Reek README](https://github.com/troessner/reek) for instance. We really took a lot of effort to make this as readable and maintainable as possible, meaning:

* there's a table of content at the top
* we touch **every** topic in the README but don't discuss it exhaustively
* instead we then link to subsequent documentation like for [Code Smells](https://github.com/troessner/reek#code-smells)
* and this subsequent documentation is - again - under "proper" source control under docs/

The problems I have with the github wiki have are:

* nobody **really** cares about. It feels like unmaintained and sloppy documentation at best in most repos
* it's not really under source control. I mean, it is, but not as part of the actual repo. This cognitive disconnect makes it even seem less important to a lot of people
* it's not suited for discussion. I've almost never seen a good discussion in a github wiki. If the docs are under docs/ it's a different story.

WDYT?

**Comment by Onumis** [comment]
I do agree that having them under /docs is a plus, but I don't really agree with your other points. 
Personally I feel like the wiki is the _de-facto_ official documentation, but I can understand how others might not feel that way (I too have seen many outdated wikis).

Having the documentation under version control will allow anyone to see the actual documentation for a specific version, and that's a big plus indeed.

That being said, I'll move every documentation into the actual repo like you suggest, and do a clean-up on the main README.
