### ISSUE TITLE
Drop support for 1.9

### ISSUE THREAD

**Issue by troessner** [whitesmith/rubycritic#68]
In the light of #67 I suggest to drop support for 1.9 completely.
Support for ruby 1.9 has been dropped for quite some while, we should let it die here as well.

From what I can see in order to make this happen we'd need to:

* remove it from travis. We could also make it an allowed failure but I don't see the point in this specific case
* major version bump 
* explicitly list it on our README

What do you guys think?

**Comment by guilhermesimoes** [comment]
[Also change this line in the gemspec.](https://github.com/whitesmith/rubycritic/blob/master/rubycritic.gemspec#L16)

I'm in favour, people should be forced to upgrade for their own good.|

**Comment by Onumis** [comment]
Agreed!

**Comment by guilhermesimoes** [comment]
[Ruby Version Usage in Commercial Projects, 2015 Edition](https://semaphoreci.com/blog/2015/12/01/ruby-version-usage-in-commercial-projects-2015-edition.html)

Hopefully those 22% will upgrade :grinning:
