### ISSUE TITLE
No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by kwerle** [whitesmith/rubycritic#7]
/Users/kwerle/.rvm/gems/ruby-2.1.2/gems/rubycritic-1.0.1/lib/rubycritic/analysers/stats.rb:21:in `read': No such file or directory @ rb_sysopen - lib/zep_solar.rb (Errno::ENOENT)
	from /Users/kwerle/.rvm/gems/ruby-2.1.2/gems/rubycritic-1.0.1/lib/rubycritic/analysers/stats.rb:21:in `methods_count'
	from /Users/kwerle/.rvm/gems/ruby-2.1.2/gems/rubycritic-1.0.1/lib/rubycritic/analysers/stats.rb:14:in `block in run'
	from /Users/kwerle/.rvm/gems/ruby-2.1.2/gems/rubycritic-1.0.1/lib/rubycritic/analysers/stats.rb:13:in `each'
	from /Users/kwerle/.rvm/gems/ruby-2.1.2/gems/rubycritic-1.0.1/lib/rubycritic/analysers/stats.rb:13:in `run'
	from /Users/kwerle/.rvm/gems/ruby-2.1.2/gems/rubycritic-1.0.1/lib/rubycritic/analysers_runner.rb:26:in `block in run'
	from /Users/kwerle/.rvm/gems/ruby-2.1.2/gems/rubycritic-1.0.1/lib/rubycritic/analysers_runner.rb:25:in `map'
	from /Users/kwerle/.rvm/gems/ruby-2.1.2/gems/rubycritic-1.0.1/lib/rubycritic/analysers_runner.rb:25:in `run'
	from /Users/kwerle/.rvm/gems/ruby-2.1.2/gems/rubycritic-1.0.1/lib/rubycritic/orchestrator.rb:15:in `critique'
	from /Users/kwerle/.rvm/gems/ruby-2.1.2/gems/rubycritic-1.0.1/lib/rubycritic/cli.rb:37:in `execute'
	from /Users/kwerle/.rvm/gems/ruby-2.1.2/gems/rubycritic-1.0.1/bin/rubycritic:5:in `<top (required)>'
	from /Users/kwerle/.rvm/gems/ruby-2.1.2/bin/rubycritic:23:in `load'
	from /Users/kwerle/.rvm/gems/ruby-2.1.2/bin/rubycritic:23:in `<main>'
	from /Users/kwerle/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/kwerle/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'

**Comment by bf4** [comment]
My guess is that this is some disconnect between a file being in version control and being on the file system.  e.g. if you delete a file but don't commit it, it will still show up in `git ls-files`, which is a good reason to check `File.readable?(path)` on every file before reading it in :)

**Comment by guilhermesimoes** [comment]
> My guess is that this is some disconnect between a file being in version control and being on the file system

In this case it's really the file that disappears during analysis. I guess `File.readable?(path)` is an easy solution... but I'd rather work on an option to exclude certain files. I don't think it's RubyCritic's job to deal with these weird edge cases.

Btw, I really appreciate your input, @bf4. I can't tell you how many times I looked into MetricFu's internals to figure out how to do something :)

**Comment by bf4** [comment]
And hopefully how not to as well :)

**Comment by guilhermesimoes** [comment]
Ha!, maybe :smile:

Well, it certainly made me avoid implementing any kind of global configuration file to configure all the integrated gems. Seemed really time consuming to keep up with all the gem changes and I was on a tight schedule (RubyCritic was my master thesis' project).

**Comment by bf4** [comment]
Well, lemme know if you want to collaborate.  MetricFu could use a lot of the fresh code and ideas in here. (Also, much prettier, sigh). BTW, have you seen quality and pronto? https://github.com/metricfu/metric_fu/wiki/Code-Tools

**Comment by Onumis** [comment]
Closing this since it's not RubyCritic's job to determine if a file went missing mid-analysis.
