### ISSUE TITLE
A new direction for RubyCritic

### ISSUE THREAD

**Issue by guilhermesimoes** [whitesmith/rubycritic#70]
As many of you probably noticed, this gem hit a halt around half a year ago.
What happened was that I made a few personal choices that left me with little time to dedicate to the project and I also lost some of the will to continue this endeavor.

From the very start I wanted this gem to be all-encompassing and cater to all kinds of developers and all kinds of projects. The problem is that there are way too many opinions and way too many approaches to accomplish similar goals and that can be paralyzing.

I've always hated unresponsive maintainers of OSS and yet I became one. All I can say is that I am truly sorry.

What's done is done though and so I am here to announce the new team that will lead RubyCritic to new heights! Give it up for @Onumis and @troessner. With their experience and your support I am certain that RubyCritic will be in good hands.

Keep on writing beautiful code!

**Comment by troessner** [comment]
Thanks for the flowers ;)

**Comment by Onumis** [comment]
Thanks, your work is in good hands! :sunglasses:
