### ISSUE TITLE
RubyCritic 1.4.0 - Reek crash

### ISSUE THREAD

**Issue by JoaoGFarias** [whitesmith/rubycritic#76]
I'm running RubyCritic version 1.4 for my project is using Ruby 1.9.3

When install rubycritic using the gem install rubycritic -v 1.4.0 command on an OSx machine.

Reek crashes during the execution. Following is the stacktrace:

/Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/smells/nested_iterators.rb:73:in `ignored_iterator?': undefined method `method_name' for (super (NoMethodError)
  (lvar :exception)):#<Class:0x007f8ddf0eaca8>
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/smells/nested_iterators.rb:65:in `find_iters_for_iter_node'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/smells/nested_iterators.rb:60:in `block in find_iters'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/smells/nested_iterators.rb:59:in `each'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/smells/nested_iterators.rb:59:in `flat_map'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/smells/nested_iterators.rb:59:in `find_iters'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/smells/nested_iterators.rb:54:in `find_deepest_iterator'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/smells/nested_iterators.rb:35:in `examine_context'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/smells/smell_detector.rb:89:in `examine'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/smell_repository.rb:59:in `block in examine'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/smell_repository.rb:58:in `each'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/smell_repository.rb:58:in `examine'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:161:in `check_smells'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:155:in `block in inside_new_context'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:167:in `push'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:153:in `inside_new_context'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:41:in `process_def'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:24:in `process'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:29:in `block in process_default'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:29:in `each'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:29:in `process_default'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:93:in `process_begin'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:24:in `process'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:29:in `block in process_default'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:29:in `each'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:29:in `process_default'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:34:in `block in process_module'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:154:in `block in inside_new_context'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:167:in `push'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:153:in `inside_new_context'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:33:in `process_module'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:24:in `process'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:29:in `block in process_default'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:29:in `each'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:29:in `process_default'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:93:in `process_begin'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/code_parser.rb:24:in `process'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/core/sniffer.rb:20:in `report_on'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/examiner.rb:41:in `block in initialize'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/source/source_repository.rb:41:in `each'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/source/source_repository.rb:41:in `each'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/reek-1.6.5/lib/reek/examiner.rb:39:in `initialize'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/rubycritic-1.4.0/lib/rubycritic/analysers/helpers/reek.rb:13:in `initialize'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/rubycritic-1.4.0/lib/rubycritic/analysers/smells/reek.rb:21:in `new'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/rubycritic-1.4.0/lib/rubycritic/analysers/smells/reek.rb:21:in `add_smells_to'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/rubycritic-1.4.0/lib/rubycritic/analysers/smells/reek.rb:14:in `block in run'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/rubycritic-1.4.0/lib/rubycritic/analysers/smells/reek.rb:13:in `each'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/rubycritic-1.4.0/lib/rubycritic/analysers/smells/reek.rb:13:in `run'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/rubycritic-1.4.0/lib/rubycritic/analysers_runner.rb:27:in `block in run'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/rubycritic-1.4.0/lib/rubycritic/analysers_runner.rb:27:in `each'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/rubycritic-1.4.0/lib/rubycritic/analysers_runner.rb:27:in `run'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/rubycritic-1.4.0/lib/rubycritic/commands/default.rb:19:in `critique'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/rubycritic-1.4.0/lib/rubycritic/commands/default.rb:15:in `execute'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/rubycritic-1.4.0/lib/rubycritic/cli/application.rb:16:in `execute'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/gems/rubycritic-1.4.0/bin/rubycritic:5:in `<top (required)>'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/bin/rubycritic:23:in `load'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/bin/rubycritic:23:in `<main>'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jgfd/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'

Is this problem happening because Reek itself [requires Ruby 2.0+](https://github.com/troessner/reek/issues/401)?

**Comment by LeeXGreen** [comment]
This is a duplicate of #45 -- it has been fixed on master but the maintainers have not specified whether they will be releasing this fix under the v1.4 branch or not.

**Comment by LeeXGreen** [comment]
You might be able to work around it by specifying the particular ref that contains this fix in your Gemfile (disclaimer -- I have not tested this specific ref):

`gem 'rubycritic', git: 'https://github.com/whitesmith/rubycritic.git', ref: 'b301ad0ff228fa2f376f24caf251bd894212460f'`

**Comment by JoaoGFarias** [comment]
Thanks @LeeXGreen, closing this issue and watching the #45
I wil try this work around.
