### ISSUE TITLE
Cannot parse colon style hashes?

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [whitesmith/rubycritic#81]
Right off the bat the gem is giving me irreconcilable errors (it doesn't understand the following code):

```ruby
module InvoicesHelper
  # Excel spreadsheet helpers
  def write_excel_format(loc)
    @workbook = Spreadsheet::Workbook.new
    if @stats.items.any?
      @stats.items.each do |category|
        # Create a worksheet for each product category
        ws = @workbook.create_worksheet(name: category[0])
 ...
```

Error:

```ruby
/home/vagrant/.rvm/gems/ruby-2.2.1@global/gems/reek-3.6.0/lib/reek/configuration/app_configuration.rb:17: warning: already initialized constant Reek::Configuration::AppConfiguration::EXCLUDE_PATHS_KEY
/home/vagrant/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/reek-3.6.0/lib/reek/configuration/app_configuration.rb:17: warning: previous definition of EXCLUDE_PATHS_KEY was here
  app/helpers/invoices_helper.rb:8 :: parse error on value ":" (tCOLON)
  skipping app/helpers/invoices_helper.rb
ERROR: parsing ruby file app/helpers/invoices_helper.rb
Racc::ParseError: app/helpers/invoices_helper.rb:8 :: parse error on value ":" (tCOLON) at:
  /home/vagrant/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/racc/parser.rb:527:in `on_error'
  /home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/ruby_parser-3.7.2/lib/ruby_parser_extras.rb:1124:in `on_error'
  /home/vagrant/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/racc/parser.rb:258:in `_racc_do_parse_c'
  /home/vagrant/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/racc/parser.rb:258:in `do_parse'
  /home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/ruby_parser-3.7.2/lib/ruby_parser_extras.rb:1036:in `block in process'
```

**Comment by troessner** [comment]
Just did the same thing using the same versions you did and couldn't reproduce it. 
Can you please post:

1.) the full stacktrace including what you type in the console
2.) the output of

```Bash
ruby -v
rubycritic -v
gem list rubycritic
gem list reek
````

**Comment by JakeTheSnake3p0** [comment]
Ruby: `ruby 2.2.1p85 (2015-02-26 revision 49769) [i686-linux]`  
Rubycritic: `RubyCritic 2.1.0`

Gem List Rubycritic:
```
*** LOCAL GEMS ***

rubycritic (2.1.0)
```

Gem List Reek:
```
*** LOCAL GEMS ***

reek (3.6.0)
```

All I had done was run `gem install rubycritic` into my @global RVM gemset.

**Comment by troessner** [comment]
No idea what's going on here but it seems like this is a problem that is specific to your machine set up, but not to rubycritic. On my machine this works as expected:

```Ruby
  ( $ ) rvm list

rvm rubies

=* ruby-2.2.1 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

  ( $ ) which rubycritic

/Users/timo/.rvm/gems/ruby-2.2.1/bin/rubycritic

  ( $ ) rubycritic foo.rb
RubyCritic can provide more feedback if you use a Git or Mercurial repository.
New critique at file:///private/tmp/tmp/rubycritic/overview.html
```

with foo.rb being:

```Ruby
module InvoicesHelper
  # Excel spreadsheet helpers
  def write_excel_format(loc)
    ws = @workbook.create_worksheet(name: category[0])
  end
end
````

I don't know much about rvm but I guess there is something wrong with your rvm set up.

**Comment by JakeTheSnake3p0** [comment]
Even stranger...I don't get any errors with the `foo.rb` example you gave. However I did an even simpler test which hopefully garners some insight:

```ruby
{:so => :what}
```

yields no errors

```ruby
{so: :what}
```

yields errors

```ruby
RubyParser::SyntaxError: Odd number (2) list for Hash. s(:array, s(:call, nil, :so)) at:
  /home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/ruby_parser-3.7.2/lib/ruby_parser_extras.rb:128:in `syntax_error'
  /home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/ruby_parser-3.7.2/lib/ruby18_parser.rb:5688:in `_reduce_492'
  /home/vagrant/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/racc/parser.rb:258:in `_racc_do_parse_c'
  /home/vagrant/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/racc/parser.rb:258:in `do_parse'
  /home/vagrant/.rvm/gems/ruby-2.2.1@pos/gems/ruby_parser-3.7.2/lib/ruby_parser_extras.rb:1036:in `block in process'
```

**Comment by Onumis** [comment]
Ok now that makes sense!
I didn't knew that: `{ "my_key": "my value" }` or `{ 'my_key': "my value" }` are valid syntax on Ruby 2.2.
Thanks, gonna add this to the todo list.

**Comment by Onumis** [comment]
I was trying to track this down now but could not reproduce the error on my machine.
I tried with RubyCritic 2.1.0, 2.2.0 and 2.3.0; Reek 3.6.0 and 3.7.1; Ruby 2.2.0p0 and 2.2.1p85...

```
class TestQuotesInSymbols
  def hash
    {
      :a => "A",
      b: "B",
      :'c' => 'C',
      :"d" => 'D',
      # new in ruby 2.2
      "e": 'E',
      'f': 'F'
    }
  end
end
```

@JakeTheSnake3p0 either the error comes from somewhere else, or something is wrong with your RVM setup as @troessner suggested.

**Comment by samstickland** [comment]
Just off the top of my head - because I'm not in front of my dev box at the
moment - I think the problem may manifest itself in named arguments?

i.e.

def simple_addition(a:, b:)
  return a + b
end

simple_addition(a: 1, b: 2)

=> 3

Sam

2015-12-18 19:03 GMT+00:00 Nuno Silva <notifications@github.com>:

**Comment by troessner** [comment]
@JakeTheSnake3p0 like i said above: This seems to be a problem with the local set up and **not** RubyCritic. We use the parser gem which can handle all of your syntax examples above regardless it it's

```Ruby
{ 'foo': 'bar' }
```
or

```Ruby
{ foo: 'bar' }
```

or any other form you might come up with.

@samstickland it has nothing to do with keyword arguments, your example passes just fine.

@JakeTheSnake3p0 could you please quickly try it with `rbenv`?
I'm confident that it will work with `rbenv` which would prove that the problem exists in your local rvm set up. Which wouldn't surprise me given rvm's state quite frankly.

**Comment by JakeTheSnake3p0** [comment]
Looks like you're right, I now have another VM to test on and I'm not getting the errors.

**Comment by troessner** [comment]
Closing this one since there is no response from the ticket creator and the evidence suggests (see above) that this is local problem, not a RubyCritic problem.
@JakeTheSnake3p0 just abandoning an issue like this is pretty rude towards the people who tried to help you.

This is closed.

**Comment by JakeTheSnake3p0** [comment]
I'm sorry you felt offended troessner, your efforts aren't in vain. I'll try and make some time to figure this out - I'm not comfortable just yet with removing RVM and using rbenv or even just for the sake of reinstalling RVM as I require RVM on a daily basis. When I have some breathing room I'll look into this again - but as you mentioned you can't reproduce, and given that the problem seems to be project-specific (I tested on a new rails app and no errors popped up) you can more than likely chalk it up to a local issue.

**Comment by JakeTheSnake3p0** [comment]
I believe I've narrowed it down further. The problem occurs when we have a string key in colon style followed by a symbol value.

```ruby
{ 'this': 'works' }
{ 'this': :fails }
```

**Comment by Onumis** [comment]
Confirmed. I've created a branch with the example file.
Here's the output:

```
$ bin/rubycritic test/samples/quotes_in_symbols.rb 
  test/samples/quotes_in_symbols.rb:6 :: parse error on value ":" (tCOLON)
  skipping test/samples/quotes_in_symbols.rb
running flay smells

running flog smells
ERROR: parsing ruby file test/samples/quotes_in_symbols.rb
Racc::ParseError: test/samples/quotes_in_symbols.rb:6 :: parse error on value ":" (tCOLON) at:
  /home/nuno/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/racc/parser.rb:527:in `on_error'
  /home/nuno/.rvm/gems/ruby-2.2.0/gems/ruby_parser-3.7.2/lib/ruby_parser_extras.rb:1124:in `on_error'
  /home/nuno/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/racc/parser.rb:258:in `_racc_do_parse_c'
  /home/nuno/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/racc/parser.rb:258:in `do_parse'
  /home/nuno/.rvm/gems/ruby-2.2.0/gems/ruby_parser-3.7.2/lib/ruby_parser_extras.rb:1036:in `block in process'
.
running reek smells
.
running complexity
ERROR: parsing ruby file test/samples/quotes_in_symbols.rb
Racc::ParseError: test/samples/quotes_in_symbols.rb:6 :: parse error on value ":" (tCOLON) at:
  /home/nuno/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/racc/parser.rb:527:in `on_error'
  /home/nuno/.rvm/gems/ruby-2.2.0/gems/ruby_parser-3.7.2/lib/ruby_parser_extras.rb:1124:in `on_error'
  /home/nuno/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/racc/parser.rb:258:in `_racc_do_parse_c'
  /home/nuno/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/racc/parser.rb:258:in `do_parse'
  /home/nuno/.rvm/gems/ruby-2.2.0/gems/ruby_parser-3.7.2/lib/ruby_parser_extras.rb:1036:in `block in process'
.
running attributes
.
running churn
.
```


I don't think this is a problem with RubyCritic itself, but with some of the tools it relies on: `flay` and `flog`.

@troessner any tips on how to proceed from here?

**Comment by troessner** [comment]
>> I don't think this is a problem with RubyCritic itself, but with some of the tools it relies on: flay and flog.

Yes, exactly. ´Reek` parses your [sample file](https://github.com/whitesmith/rubycritic/blob/a8e1a4e351c7ea6344f2fe395d7225bfc0397900/test/samples/quotes_in_symbols.rb) just fine, flay and flog crash on it. 
The reason is quite simple: `Reek` relies on the awesome [parser](https://github.com/whitequark/parser)
whereas `flay` and `flog` rely on the [ruby_parser gem](https://github.com/seattlerb/ruby_parser). 

So the way to fix this would be to either 

[1] fix `ruby_parser` 
[2] OR make `flay` and `flog` use `parser`

Both [1] and [2] are highly complex, but rewarding problems.

Who wants to take a shot at it? :)

**Comment by Onumis** [comment]
At least they are aware: https://github.com/seattlerb/ruby_parser/issues/175

**Comment by eljojo** [comment]
Hi everyone, I just faced the same issue.
setting ``gem 'ruby_parser', '3.7.2'`` in my gemfile fixed the bug.

Now I just have to wait for ``ruby_parser`` to support the save navigation operator :(

**Comment by troessner** [comment]
>> Now I just have to wait for ruby_parser to support the save navigation operator :(

Got added 3 days ago:

https://github.com/seattlerb/ruby_parser/commit/da22d1e256305dff2bb549e9f13fcf9f69c43bb2

but no release in sight yet :-/
