### ISSUE TITLE
add a console report

### ISSUE THREAD

**Issue by jbodah** [whitesmith/rubycritic#89]
AFAIK the only outputs we have are json file and html file. It would be nice to just enable it to print a summary to the screen instead of to a file

Might take a go at this some time soon, just want to document it

**Comment by troessner** [comment]
Yes, that would be really nice, I agree.

>> Might take a go at this some time soon

By all means, please go ahead ;)

**Comment by troessner** [comment]
Closing this, since #91 has been merged.
