### ISSUE TITLE
Explain our core metrics or link to explanations

### ISSUE THREAD

**Issue by troessner** [whitesmith/rubycritic#97]
I believe right now we are doing a pretty bad job when it comes to this. For most users quite a few metrics are probably obscure.

Let's change that!

E.g. the turbulence gem has a great explanation of [churn vs complexity](https://github.com/chad/turbulence), lets pack our docs with links like that ;)

**Comment by Onumis** [comment]
I agree. There's a serious lack of documentation (#63, #77)

Additionally I think we should make RubyCritic proud if itself. By this I mean that there are a lot of code smells that show up if you run RubyCritic on `/lib``. Most of them are easily solvable, like adding descriptive comments to classes. (Maybe this is a separate issue?)

This will in turn make the code more easy to understands for those outside this context (static-analysis). 
Note that this is different from #93 - even the internal stuff of RubyCritic should be well documented and following the very code standards it suggests.

**Comment by troessner** [comment]
Couldnt agree more. Eat your own dogfood. We should make all the we use in RubyCritic part of our own CI process. At least where it makes that they can fail our build. "Reek" would be one, not sure about flay / flog since they have different semantics

**Comment by Onumis** [comment]
Expanded on wiki to include these: https://github.com/whitesmith/rubycritic/wiki/Core-Metrics,-Score-and-Rating
